### ISSUE TITLE
Local time download not supported

### ISSUE THREAD

**Issue by jlprol** [Matt-Brigida/EIAdata#10]
Thank you for this package.

Some data are provided by the EIA in UTC and local time, e.g:

```
getCatEIA(key = key, cat = 3389939)

series_id                                             name  f         units               updated
1  EBA.FLA-ALL.D.H   Demand for Florida (region), hourly - UTC time  H megawatthours 01-MAY-20 09.05.09 AM
2 EBA.FLA-ALL.D.HL Demand for Florida (region), hourly - local time HL megawatthours 01-MAY-20 09.05.09 AM
```

whereas the UTC time download works well, the local time (HL) call gives an error

```
getEIA(key = key, ID = "EBA.CAL-ALL.D.HL")
"ERROR: The last character of your ID is not one of the possible sampling frequencies (A, Q, M, W, D, or H)"
```

**Comment by Matt-Brigida** [comment]
I assume you are using the CRAN version?  This was [fixed in this commit](https://github.com/Matt-Brigida/EIAdata/commit/3d6cce1c995995a2b75a9f17641fbb6f393140a5).  You can install from github until I get the latest version on CRAN.  And thanks for opening the issue.

**Comment by jlprol** [comment]
Great, thanks!
