### ISSUE TITLE
getEIA producing error

### ISSUE THREAD

**Issue by BuddyAnderson** [Matt-Brigida/EIAdata#14]
When running:

getEIA(ID = "EBA.US48-ALL.D.H", key = key)

I receive error:

Opening and ending tag mismatch: link line 59 and head
Failed to parse QName 'fb:like:'
Namespace prefix fb for like:layout on a is not defined
Specification mandates value for attribute compensate-for-scrollbar
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
xmlParseEntityRef: no name
Entity 'rsaquo' not defined
Entity 'rsaquo' not defined
Entity 'rsaquo' not defined
Entity 'rsaquo' not defined
Entity 'nbsp' not defined
Opening and ending tag mismatch: input line 59 and form
Opening and ending tag mismatch: input line 59 and p
Opening and ending tag mismatch: input line 59 and div
Opening and ending tag mismatch: form line 59 and div
Opening and ending tag mismatch: p line 59 and div
Opening and ending tag mismatch: div line 59 and section
Opening and ending tag mismatch: section line 59 and body
Opening and ending tag mismatch: div line 59 and html
EndTag: '</' not found

Please advise?

**Comment by Matt-Brigida** [comment]
Running the latest CRAN version of EIAdata under Arch Linux:

`getEIA(ID = "EBA.US48-ALL.D.H", key = key)`
>                    EBA.US48.ALL.D.H
> 2015-07-01 05:00:00           162827
> 2015-07-01 06:00:00           335153
> 2015-07-01 07:00:00           333837
> 2015-07-01 08:00:00           398386
> 2015-07-01 09:00:00           388954
> 2015-07-01 10:00:00           392487

Can you provide your `sessionInfo()`?  Maybe you are running a different version of XML which is causing the issue.

**Comment by Matt-Brigida** [comment]
Just tested with the latest CRAN version of XML (`3.99-0.6`) and can't reproduce your error.  If you post `sessionInfo()` I'll take a look, but I don't think this is an `EIAdata` problem.  Maybe it is an issue with your XML install. You may want to try and reinstall the XML package.

**Comment by BuddyAnderson** [comment]
Matt, reinstalling XML worked like a charm, thank you for the suggestion! Also, it is worth mentioning that EIAdata has proven extremely helpful.

**Comment by Matt-Brigida** [comment]
Great to hear you got it working, and that you have found EIAdata useful!
