### ISSUE TITLE
Create call using XML for a specified range

### ISSUE THREAD

**Issue by statistical-lusardi** [Matt-Brigida/EIAdata#15]
I am interested in specifying a date range so as to not download the entire dataset for each time getEIA is performed. I found that there was no apparent way to specify a date range to collect a certain range of data using the xmlparse function. Is there a work around?

**Comment by Matt-Brigida** [comment]
My apologies on addressing this issue sooner.  I'll being doing some work on the package over the next week, so I'll take a look at what can be done.

**Comment by Matt-Brigida** [comment]
It looks like there is a way in the APIv2.
