### ISSUE TITLE
Outcomes are all NAs

### ISSUE THREAD

**Issue by hm-yuan** [Matt-Brigida/EIAdata#8]
When I run
`getEIA(ID = "PET.RWTC.D", key = key)`
I get all the dates correct, while the values are all NAs

**Comment by sawyervillers** [comment]
I was able to download timeseries data for PET.RWTC.D for Jan.3.1986 thru Feb.25.2020.

**Comment by Matt-Brigida** [comment]
I wasn't able to reproduce your issue:

```R
> head(getEIA("PET.RWTC.D", key = key))
##            PET.RWTC.D
## 1986-01-02      25.56
## 1986-01-03      26.00
## 1986-01-06      26.53
## 1986-01-07      25.85
## 1986-01-08      25.87
## 1986-01-09      26.03
```
```R
sum(is.na(getEIA("PET.RWTC.D", key = key))
## 0
```

If the problem persists feel free to reopen an issue.

**Comment by code-stu** [comment]
Thanks a lot for this convenient tool !
I reinstall the package, but still get NAs. This is weird since it worked well for me in a long time.
Could it be masked by other packages? or my IP is blocked by EIA?

**Comment by sawyervillers** [comment]
I had a problem with masking; I had to load EIAdata *before* loading tidyverse.  If you are returning dates, it's probably not an API issue.
